import type { HrPayrollPaymentConceptDefinition } from '../../types/hr-payroll';

export const DEFAULT_PAYMENT_CONCEPTS: HrPayrollPaymentConceptDefinition[] = [
  { code: 'INGRESO_ORDINARIO_FIJO', name: 'Ingreso ordinario fijo', type: 'INCOME', socialSecurityApplicable: true, trainingContributionApplicable: true, incomeTaxTreatment: 'REGULAR_FIXED', incomeTaxDeductible: false, sourceReference: 'Contrato y regla laboral vigente' },
  { code: 'INGRESO_ORDINARIO_VARIABLE', name: 'Ingreso ordinario variable', type: 'INCOME', socialSecurityApplicable: true, trainingContributionApplicable: true, incomeTaxTreatment: 'REGULAR_VARIABLE', incomeTaxDeductible: false, sourceReference: 'Contrato y regla laboral vigente' },
  { code: 'HORAS_EXTRA_APROBADAS', name: 'Horas extra aprobadas', type: 'INCOME', socialSecurityApplicable: true, trainingContributionApplicable: true, incomeTaxTreatment: 'REGULAR_VARIABLE', incomeTaxDeductible: false, sourceReference: 'Código del Trabajo y regla laboral vigente' },
  { code: 'PERMISO_PAGADO_APROBADO', name: 'Permiso pagado aprobado', type: 'INCOME', socialSecurityApplicable: true, trainingContributionApplicable: true, incomeTaxTreatment: 'REGULAR_FIXED', incomeTaxDeductible: false, sourceReference: 'Política laboral validada' },
  { code: 'BONO_OCASIONAL', name: 'Bono ocasional', type: 'INCOME', socialSecurityApplicable: true, trainingContributionApplicable: true, incomeTaxTreatment: 'OCCASIONAL', incomeTaxDeductible: false, sourceReference: 'Naturaleza del pago y soporte legal validado' },
  { code: 'VACACIONES_PAGADAS', name: 'Vacaciones pagadas', type: 'INCOME', socialSecurityApplicable: true, trainingContributionApplicable: true, incomeTaxTreatment: 'OCCASIONAL', incomeTaxDeductible: false, sourceReference: 'Código del Trabajo y soporte tributario validado' },
  { code: 'INCENTIVO_OCASIONAL', name: 'Incentivo ocasional', type: 'INCOME', socialSecurityApplicable: true, trainingContributionApplicable: true, incomeTaxTreatment: 'OCCASIONAL', incomeTaxDeductible: false, sourceReference: 'Naturaleza del pago y soporte legal validado' },
  { code: 'VIATICOS_ALIMENTACION', name: 'Viáticos de alimentación', type: 'INCOME', socialSecurityApplicable: false, trainingContributionApplicable: false, incomeTaxTreatment: null, incomeTaxDeductible: false, sourceReference: 'Política de viáticos y comprobantes' },
  { code: 'VIATICOS_TRANSPORTE', name: 'Viáticos de transporte', type: 'INCOME', socialSecurityApplicable: false, trainingContributionApplicable: false, incomeTaxTreatment: null, incomeTaxDeductible: false, sourceReference: 'Política de viáticos y comprobantes' },
  { code: 'VIATICOS_HOSPEDAJE', name: 'Viáticos de hospedaje', type: 'INCOME', socialSecurityApplicable: false, trainingContributionApplicable: false, incomeTaxTreatment: null, incomeTaxDeductible: false, sourceReference: 'Política de viáticos y comprobantes' },
  { code: 'VIATICOS_OTROS', name: 'Otros viáticos documentados', type: 'INCOME', socialSecurityApplicable: false, trainingContributionApplicable: false, incomeTaxTreatment: null, incomeTaxDeductible: false, sourceReference: 'Política de viáticos y comprobantes' },
  { code: 'REEMBOLSO_DEPRECIACION', name: 'Pago o reembolso de depreciación', type: 'INCOME', socialSecurityApplicable: false, trainingContributionApplicable: false, incomeTaxTreatment: null, incomeTaxDeductible: false, sourceReference: 'Contrato, política de activos y soporte contable' },
  { code: 'FONDO_PENSION_AUTORIZADO', name: 'Fondo de pensión autorizado', type: 'DEDUCTION', socialSecurityApplicable: false, trainingContributionApplicable: false, incomeTaxTreatment: null, incomeTaxDeductible: true, sourceReference: 'Soporte legal y documental de la deducción' },
  { code: 'APORTE_AHORRO_AUTORIZADO', name: 'Aporte de ahorro autorizado', type: 'DEDUCTION', socialSecurityApplicable: false, trainingContributionApplicable: false, incomeTaxTreatment: null, incomeTaxDeductible: true, sourceReference: 'Soporte legal y documental de la deducción' },
];
